server:
  port: 8080
  servlet:
    context-path: /POD_BookingSystem

spring:
  datasource:
    url: "jdbc:mysql://14.225.206.250:3306/POD_BookingSystem"
    username: root
    password: root@123
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
jwt:
  signKey: "XyoNeBIfTwb3rCdDFFnzcXQHcyaX7G+y/nTn5loDeYWuf4hPFMsfwEfjsM5qGz+i"
  valid-duration: 100
  refreshable-duration: 120

logging:
  level:
    root: INFO
    com.example.identity_service: DEBUG

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

